### ISSUE TITLE
aws-external-dns.yaml fails on Argocd

### ISSUE THREAD

**Issue by matty1979** [argoflow/argoflow-aws#20] opened 2021-04-19 17:22 UTC
`Failed build model due to couldn't auto-discover subnets: unable to discover at least one subnet`

And 
`time="2021-04-19T17:20:35Z" level=fatal msg="flag parsing error: required flag --source not provided"`

**Comment by DavidSpek** [comment] 2021-04-19 17:50
I'll look through the docs to try and find a solution tomorrow, unless you are able to find the solution before then.

**Comment by DavidSpek** [comment] 2021-04-20 09:36
This was caused by an incorrect manifest which is now fixed.

**Closed** 2021-04-20 09:36 UTC
